name: pablof - milestone

on:
  pull_request:
  milestone:
    types: [created, opened, edited, closed, deleted]

jobs:
  pablof-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: a24k/pablof@milestone-issue-project
        with:
          token: ${{ secrets.GH_TOKEN }}
          project: ${{ secrets.PROJECT_ID }}
