name: pablof

on:
  pull_request:
  milestone:
    types: [created, opened, edited, closed, deleted]

jobs:
  pablof:
    runs-on: ubuntu-latest
    steps:
      - uses: a24k/pablof@v0
        with:
          token: ${{ secrets.GH_TOKEN }}
