name: pablof

on:
  pull_request:
  issues:
    types: [opened]
  milestone:
    types: [created, opened, edited, closed, deleted]

jobs:
  pablof:
    runs-on: ubuntu-latest
    steps:
      - uses: a24k/pablof@derive-issue-body
        with:
          token: ${{ secrets.GH_TOKEN }}
